# Generated by Django 5.2.1 on 2025-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
