# Generated by Django 5.2.1 on 2025-06-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_alter_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
    ]
